enum VDoEvent{
    BACKEND_INITED = 'BACKEND_INITED',
    OPEN_CAMERA  = 'OPEN_CAMERA',
    CLOSE_CAMERA = 'CLOSE_CAMERA',
    
    UPDATE_IMAGE = 'UPDATE_IMAGE',
    TAKE_PHOTO   = 'TAKE_PHOTO',
    RECORD_VIDEO = 'RECORD_VIDEO',

    SET_SMOOTHNESS = 'SET_SMOOTHNESS',
    SET_BRIGHTNESS = 'SET_BRIGHTNESS',
    SET_SATURAION  = 'SET_SATURATION',
    SET_CONTRAST   = 'SET_CONTRAST',
    SET_SHARPNESS  = 'SET_SHARPNESS',
    SET_HUE        = 'SET_HUE'

}

export { VDoEvent }