enum VDoEvent{
    OPEN_CAMERA  = 'OPEN_CAMERA',
    CLOSE_CAMERA = 'CLOSE_CAMERA',
    
    TAKE_SCREEN_SHOT   = 'TAKE_SCREEN_SHOT',
    START_RECORD_VIDEO = 'START_RECORD',
    FINISH_RECORD_VIDEO= 'FINISH_RECORD_VIDEO',

    SET_SMOOTHNESS = 'SET_SMOOTHNESS',
    SET_BRIGHTNESS = 'SET_BRIGHTNESS',
    SET_SATURAION  = 'SET_SATURATION',
    SET_CONTRAST   = 'SET_CONTRAST',
    SET_SHARPNESS  = 'SET_SHARPNESS',
    SET_HUE        = 'SET_HUE'

}

export { VDoEvent }